name: lint
description: Runs all the linters in the codebase
inputs:
  node-version:
    description: "The node.js version to use"
    required: false
    default: "22"
runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
    - name: Run yarn install
      uses: ./.github/actions/yarn-install
    - name: Run shellcheck
      shell: bash
      run: yarn shellcheck
    - name: Lint code
      shell: bash
      run: ./.github/workflow-scripts/exec_swallow_error.sh yarn lint --format junit -o ./reports/junit/eslint/results.xml
    - name: Lint file structure
      shell: bash
      run: ./.github/workflow-scripts/lint_files.sh
    - name: Run flowcheck
      shell: bash
      run: yarn flow-check
    - name: Run typescript check
      shell: bash
      run: yarn test-typescript
    - name: Check formatting
      shell: bash
      run: yarn run format-check
    - name: Lint markdown
      shell: bash
      run: yarn run lint-markdown
